version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directories:
      - "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    labels:
      - "npm"
      - "Dependabot"
    assignees:
      - "mhmdio"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
    labels:
      - "github-actions"
      - "Dependabot"
    assignees:
      - "mhmdio"
